# preload = ~/.config/backgrounds/f40.jpg
# wallpaper = , ~/.config/backgrounds/f40.jpg
wallpaper {
  monitor = 
  path = ~/.config/backgrounds/f40.jpg
  fit_mode = cover
}
#preload = ~/documents/personal/Wallpapers/gt500-69-1.png
#wallpaper = , ~/documents/personal/Wallpapers/gt500-69-1.png
#preload = ~/documents/personal/Wallpapers/Hoonicorn.jpg
#wallpaper = , ~/documents/personal/Wallpapers/Hoonicorn.jpg
# preload = ~/documents/personal/Wallpapers/mr2-rojo.jpg
# wallpaper = , ~/documents/personal/Wallpapers/mr2-rojo.jpg
