# Carga TPM (Tmux Plugin Manager)
set -g @plugin 'tmux-plugins/tpm'

# Opciones de compatibilidad y navegación
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-resurrect'
# set -g @plugin 'alexwforsythe/tmux-which-key'

# Tema Kanagawa (manteniéndolo para que haga juego con NVIM/Ghostty)
set -g @plugin 'Nybkox/tmux-kanagawa'
set -g @kanagawa-theme 'wave'
set -g @kanagawa-plugins "git"
# set -g @kanagawa-plugins "cwd time"
set -g @kanagawa-ignore-window-colors true

# --- Manejo de terminal y colores ---
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*:Tc"
set -s extended-keys off

# --- CORRECCIÓN WAYLAND / HYPRLAND ---
# Modo vim y uso de wl-copy en lugar de clip/xclip
set -g mode-keys vi
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "wl-copy"

# --- ATAJOS VANILLA MEJORADOS ---
# Mantenemos Prefix por defecto (Ctrl-b)
# Mantenemos % y " pero los hacemos abrir en el directorio actual
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# --- EXTRAS ---
# Ventana flotante (Scratchpad) con Alt+g
bind-key -n M-g if-shell -F '#{==:#{session_name},scratch}' {
  detach-client
} {
  display-popup -d "#{pane_current_path}" -E "tmux new-session -A -s scratch"
}

# Soporte para ratón
set -g mouse on

# Posición de la barra de estado
set -g status-position top

# Matar todas las sesiones excepto la actual
bind K confirm-before -p "Kill all other sessions? (y/n)" "kill-session -a"

# Índices lógicos (Empezar en 1 en lugar de 0)
set -g base-index 1
setw -g pane-base-index 1

# Inicializar TPM (Debe estar al final)
run '~/.tmux/plugins/tpm/tpm'
